### ISSUE TITLE
Infografia_IrvingFernandoReyesPacheco

### ISSUE THREAD

**Issue by IrvingFernand0** [SistemasTecTlaxiaco/actividad-1-infografia-IrvingFernand0#2]
[Infografia_CicloDeDesarrolloDeSoftware_IrvingFernando.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-IrvingFernand0/files/9420354/Infografia_CicloDeDesarrolloDeSoftware_IrvingFernando.pdf)

**Comment by mel-16** [comment]
Cuenta con Faltas de ortografías  según las reglas gramaticales.
Cal:17

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
